/* Generated by tools/generate-service-worker.js. Do not edit by hand. */
const APP_CACHE_NAME = 'cognitive-app-1791294274708';
const MEDIA_CACHE_NAME = 'cognitive-media-v1';
const APP_ASSET_PATHS = [
  {
    "path": ".nojekyll",
    "hash": "43392b4e290e3730674e985cc7b93d291a34a5ae"
  },
  {
    "path": "CONTEXT.md",
    "hash": "cb44e96806b4089838f1eeddb0160d6a5ebf2296"
  },
  {
    "path": "CONTINUITY.md",
    "hash": "bcfac1491e604a1c3060a544240a86476289c584"
  },
  {
    "path": "GAME_MODULES.md",
    "hash": "403e9c29b64fbabc090d861ced31f6ac0119dca1"
  },
  {
    "path": "README.md",
    "hash": "e22878d1e6295ad62927773153e6837dedb89ad4"
  },
  {
    "path": "css/different.css",
    "hash": "d73658affc94bd30dda29aaf85758a5408bc693f"
  },
  {
    "path": "css/dual-nback.css",
    "hash": "738238a0fb620789fadfa7c8b538f332ab9c297c"
  },
  {
    "path": "css/food.css",
    "hash": "a7f07b1be3d05428af2d1693a3338a8ab0d2c97d"
  },
  {
    "path": "css/game-screen.css",
    "hash": "f6cc3ffd734e06dad92c6651a6acb4a04b031da4"
  },
  {
    "path": "css/gng.css",
    "hash": "cf479aac8134c53d904686fa94540c6e50dcdc0a"
  },
  {
    "path": "css/nback.css",
    "hash": "0846319909ef94b78c9b49f9a883315c4e489772"
  },
  {
    "path": "css/pairs.css",
    "hash": "25ebf866948c6759f652952711d1cfde65a18d56"
  },
  {
    "path": "css/reality.css",
    "hash": "70a92176b5eab2ebc7bf4ae11c8dedbec0e0f1e3"
  },
  {
    "path": "css/shared.css",
    "hash": "ba9acc69c41c4f3a71900fe2e82408ff4ed48c05"
  },
  {
    "path": "css/shopping.css",
    "hash": "80477a743e7368504057fe1644b3755f1212d2da"
  },
  {
    "path": "css/stroop.css",
    "hash": "bd9f140959994cb6207a5ed594cd0c552f77051d"
  },
  {
    "path": "css/unified.css",
    "hash": "25f38a75c118387029a04dd28d2f283dcfb2760f"
  },
  {
    "path": "css/variables.css",
    "hash": "28ce231eb3a53a00512466eb10852a21d6aba368"
  },
  {
    "path": "docs/adr/0001-shared-game-screen.md",
    "hash": "50468cce490e6d1590449e501c1babe5e196cc51"
  },
  {
    "path": "docs/adr/0002-face-set-is-a-game-agnostic-asset-pack.md",
    "hash": "b79cca25125e7bfeaaf8d3721af1965ae572e07c"
  },
  {
    "path": "docs/adr/0003-emotional-face-word-stroop-v1.md",
    "hash": "9e1f94b1699b234a99301ea373f138abbba5de82"
  },
  {
    "path": "docs/research/emotional-stroop.md",
    "hash": "f4a496cf132ed8c8af98aa40c0271bb28a45b674"
  },
  {
    "path": "icon-maskable.svg",
    "hash": "d6c6e5706917a4d63de85f3e901749fc6e1cec90"
  },
  {
    "path": "icon.svg",
    "hash": "7e11d1846a365941907ce4d70f605159c1e2417c"
  },
  {
    "path": "index.html",
    "hash": "85f0531582107510cd1da8479937aff499ff3efc"
  },
  {
    "path": "js/app-chrome.js",
    "hash": "9ede6b6977bf985b32d1f79329582738768f5639"
  },
  {
    "path": "js/boot.js",
    "hash": "224711bc3454b0a5e482224fe686e4d9b85e6841"
  },
  {
    "path": "js/celebrity-faces.js",
    "hash": "3f38289bd332cfbbb828c180fe9b80f0ef9caceb"
  },
  {
    "path": "js/food/audio.js",
    "hash": "d2b48968aaa3d0255d99c56b7ca9d7533a8208c0"
  },
  {
    "path": "js/food/different-view.js",
    "hash": "796fa19b453c2184337eac90f3ce9231fedfefcf"
  },
  {
    "path": "js/food/different.js",
    "hash": "9c9adf9af1d4a231ba907064b850e86369838989"
  },
  {
    "path": "js/food/dual-nback-logic.js",
    "hash": "0db2e273503111fcaf24b35c70fba8a311a8f765"
  },
  {
    "path": "js/food/dual-nback-screen.js",
    "hash": "a6d5daefa7864e43ac7a540225c0a85e60a71242"
  },
  {
    "path": "js/food/dual-nback-view.js",
    "hash": "50c42103ba51ba1f359891d6b625e2492fc5163c"
  },
  {
    "path": "js/food/dual-nback.js",
    "hash": "c386810ec04ec2984dc520088ab96c6625545d1b"
  },
  {
    "path": "js/food/food-data.js",
    "hash": "b500d02922f5919222648da1a960fa50ce320b54"
  },
  {
    "path": "js/food/food-logic.js",
    "hash": "c7ba97e6693ae89fa913c7b0af939a5c861f1f82"
  },
  {
    "path": "js/food/food-screen.js",
    "hash": "49e58869c306dfdd9a8f9c312be2d1971497c4fa"
  },
  {
    "path": "js/food/food-view.js",
    "hash": "8e7d16d385d7224adb8635c76c75591211d7326a"
  },
  {
    "path": "js/food/food.js",
    "hash": "81edcd3ab73714a2c2a749f498cd1346b78d41b7"
  },
  {
    "path": "js/food/gng-logic.js",
    "hash": "378acb24372f1e3f3ad7d85ce187a7bed7160468"
  },
  {
    "path": "js/food/gng-screen.js",
    "hash": "898489f5625ffc7ac061931ac4686e9863b76b1d"
  },
  {
    "path": "js/food/gng-view.js",
    "hash": "41964db27b576aff7e16bdc409f3d602a5ec41c1"
  },
  {
    "path": "js/food/gng.js",
    "hash": "1353cf08fb25853e5c2b90d7b472e2f775d7d986"
  },
  {
    "path": "js/food/main.js",
    "hash": "e27df5d457fb7e0029439c003df87d89eb5ea5a3"
  },
  {
    "path": "js/food/message.js",
    "hash": "50be0fe5d14b575d41cd70f409caec76fe44aa6c"
  },
  {
    "path": "js/food/name-visibility.js",
    "hash": "7c66de3e17ed919a2ddeef208d05ebe893d1ec60"
  },
  {
    "path": "js/food/nback-audio-map.js",
    "hash": "b9252e656f7aff0dfc9737f98b2fd78be352d0a9"
  },
  {
    "path": "js/food/nback-screen.js",
    "hash": "69d57e4dad34596bbc7d592943dd515143b7e485"
  },
  {
    "path": "js/food/nback-view.js",
    "hash": "2d2fb21add74a27a67b52d34b4a299b2f2d2e085"
  },
  {
    "path": "js/food/nback.js",
    "hash": "d3c94a90df98b77d19fea9d8c41b2af87950e4d9"
  },
  {
    "path": "js/food/pairs-logic.js",
    "hash": "920971612e9e26d12f25c45503ab38a386a088bd"
  },
  {
    "path": "js/food/pairs-settings.js",
    "hash": "8ae6e04ad1b496723efc66bcdc0137039ece1259"
  },
  {
    "path": "js/food/pairs-view.js",
    "hash": "680e312b1f6820fe739bbcd5da1487964f35ed61"
  },
  {
    "path": "js/food/pairs.js",
    "hash": "7e9e435dda8dcf6141bd00799a531b27b139f7c9"
  },
  {
    "path": "js/food/palm-screen.js",
    "hash": "ac78b33f9c0f75406089d6eaed16a4bfc2c9b36d"
  },
  {
    "path": "js/food/prefs.js",
    "hash": "1b76701826d1523f3838f5e15ddc0bdee34b1327"
  },
  {
    "path": "js/food/sequence.js",
    "hash": "05c43bca74ae2653d42c30c3b211afaaa3309f3e"
  },
  {
    "path": "js/food/shopping-logic.js",
    "hash": "3e1511f53cefaa733a97e4292cfee385107842fd"
  },
  {
    "path": "js/food/shopping-screen.js",
    "hash": "13ba5428dfef5d625b1da4b4f5c61ee4c203948a"
  },
  {
    "path": "js/food/shopping-view.js",
    "hash": "e6ca72b90f825296d50a2b3f258f86ef99bd05e3"
  },
  {
    "path": "js/food/shopping.js",
    "hash": "87dc2ffad360d0e3f8ad8c0fa537815fa045382d"
  },
  {
    "path": "js/food/stroop-logic.js",
    "hash": "f32718560e8c1d1a25cdfd51c44793f51ce77cce"
  },
  {
    "path": "js/food/stroop-screen.js",
    "hash": "7713109ff833c482c98f8785277add7c4355391a"
  },
  {
    "path": "js/food/stroop-session.js",
    "hash": "4647a2e2762802cce053d9b77ec9637e86dffa1e"
  },
  {
    "path": "js/food/stroop-view.js",
    "hash": "9656ead092a9c8bdac2f6edcd5960aa6e7d70eb9"
  },
  {
    "path": "js/food/stroop.js",
    "hash": "bbe816fefff2a9c26e4fdec7492214aab7619c79"
  },
  {
    "path": "js/food/ui.js",
    "hash": "4358ba52f850e16abac094e212a5c1ad6ba5f0ec"
  },
  {
    "path": "js/game-registry.js",
    "hash": "b2000151d53454b0466f907951b494244cbaffbb"
  },
  {
    "path": "js/game-screen.js",
    "hash": "e298fae863370683de6ce8023579c083bc396f51"
  },
  {
    "path": "js/keyboard.js",
    "hash": "89d41441c8c569d007cc06240683ad20be0f8bfa"
  },
  {
    "path": "js/layout.js",
    "hash": "ef5009f2f2f54af71bc79771ce970eb36c9dba4b"
  },
  {
    "path": "js/palm.js",
    "hash": "c819ca5af6410ca62f144f0db46065f5eb02a39b"
  },
  {
    "path": "js/reality.js",
    "hash": "535e0214b2b5d580857bcd6b37375afc7eff4f2e"
  },
  {
    "path": "js/router.js",
    "hash": "4465aebf806e14c8fd8198041b5ae0971d30bced"
  },
  {
    "path": "js/session.js",
    "hash": "a8def11af188cf8ad3dc908f868d6cea769d8636"
  },
  {
    "path": "js/settings-layout.js",
    "hash": "327a66fa146ac66546ece588dd53a65b72ac2964"
  },
  {
    "path": "js/settings.js",
    "hash": "4832e69dacff549d396d45cc59329781831c593e"
  },
  {
    "path": "js/timer.js",
    "hash": "fefb533533ce765bf99c65073fecd6f2084376b4"
  },
  {
    "path": "js/update-flow.js",
    "hash": "a3cc4e706ab3ed2b04a8d9e6f5f055ebe17d119a"
  },
  {
    "path": "js/worker-runtime.js",
    "hash": "41226c92c123696b6283d16b4b30167fc53c5ac5"
  },
  {
    "path": "manifest.webmanifest",
    "hash": "9056bc83be1ed09aebf2c20d827142f2743755c9"
  }
];
const MEDIA_ASSET_PATHS = [
  {
    "path": "assets/audio/background.mp3",
    "hash": "efe01a681d664ec252261a1040c6f33ca037c3d0"
  },
  {
    "path": "assets/audio/nback/000.mp3",
    "hash": "99660bea1150a42fc8298d7daff0dc6781c2680d"
  },
  {
    "path": "assets/audio/nback/001.mp3",
    "hash": "6ddc65061395189c91c43395cf0be4d7b04529d9"
  },
  {
    "path": "assets/audio/nback/002.mp3",
    "hash": "abc768f30c08e77373d18ac031d8badd10bedd81"
  },
  {
    "path": "assets/audio/nback/003.mp3",
    "hash": "7805a4b9a8521c32ad8585c35dca4b2037d86081"
  },
  {
    "path": "assets/audio/nback/004.mp3",
    "hash": "f7b49269ae00dec432a22ed27b64e23a9b06a7fd"
  },
  {
    "path": "assets/audio/nback/005.mp3",
    "hash": "10967decd5d3e2231f37e5305ecabfda98e87848"
  },
  {
    "path": "assets/audio/nback/006.mp3",
    "hash": "4a102591cbc85dfeff32fd0462ccbd374b8853eb"
  },
  {
    "path": "assets/audio/nback/007.mp3",
    "hash": "32a8ed7241ba72d4f2a58b5839ad7564d976d140"
  },
  {
    "path": "assets/audio/nback/008.mp3",
    "hash": "d7d5ddd3b48a7a570072d21186b4e32ea8e48957"
  },
  {
    "path": "assets/audio/nback/009.mp3",
    "hash": "fe91fa5956f99deceaad509a7fb726fd5bb3152c"
  },
  {
    "path": "assets/audio/nback/010.mp3",
    "hash": "f5d1ebcd6b69828e41bb6344b82453e8db2e7e55"
  },
  {
    "path": "assets/audio/nback/011.mp3",
    "hash": "3a742a9df108a442a1696ac93c37905e17af5587"
  },
  {
    "path": "assets/audio/nback/012.mp3",
    "hash": "81c0b9033b1a02d5332f09994ad586408be09091"
  },
  {
    "path": "assets/audio/nback/013.mp3",
    "hash": "b39c563939f9917a6362f9caa03cbb5b2d361d9f"
  },
  {
    "path": "assets/audio/nback/014.mp3",
    "hash": "97fcfefac5363e6a822302fd7444add9af2bcb94"
  },
  {
    "path": "assets/audio/nback/015.mp3",
    "hash": "815cbbcb4d2d7efb7529ec6a6c7d8939d4c4065d"
  },
  {
    "path": "assets/audio/nback/016.mp3",
    "hash": "def93818e01d10cf4546db3254bb69f2c25852af"
  },
  {
    "path": "assets/audio/nback/017.mp3",
    "hash": "ea69e327ad8c2c0330aeedb37bb36ce4f6410bea"
  },
  {
    "path": "assets/audio/nback/018.mp3",
    "hash": "fbd750f55a392500407fe42e33417871afc60671"
  },
  {
    "path": "assets/audio/nback/019.mp3",
    "hash": "61f1ce6704e3983d335b1a812229567fbc86cd2d"
  },
  {
    "path": "assets/audio/nback/020.mp3",
    "hash": "b33bce818e7b49598c666826eb31e355717d17f8"
  },
  {
    "path": "assets/audio/nback/021.mp3",
    "hash": "5c467f60d8e975811bc83c9cbb1dde3af867d6c8"
  },
  {
    "path": "assets/audio/nback/022.mp3",
    "hash": "291ad51f96cb421d66aec08cfdda331a53faff22"
  },
  {
    "path": "assets/audio/nback/023.mp3",
    "hash": "f3ba29d716cbc9cef30cfa8e1a8890c59459a13d"
  },
  {
    "path": "assets/audio/nback/024.mp3",
    "hash": "f3f140682239012dab44a7502acf0f4146b3785a"
  },
  {
    "path": "assets/audio/nback/025.mp3",
    "hash": "f22fa8886b6beca9c26df44b08c03c20cc6d4073"
  },
  {
    "path": "assets/audio/nback/026.mp3",
    "hash": "7489b00ca7487e43d67156ac742ab2910815a9bb"
  },
  {
    "path": "assets/audio/nback/027.mp3",
    "hash": "e148a8c8dd2460bf767698a9c80ad6428bc9ad03"
  },
  {
    "path": "assets/audio/nback/028.mp3",
    "hash": "ab8ceeb43d8a62ecf36cfc218caa068d0a81fd91"
  },
  {
    "path": "assets/audio/nback/029.mp3",
    "hash": "f202ac46345806f15c32368630a306308b987314"
  },
  {
    "path": "assets/audio/nback/030.mp3",
    "hash": "9c47630b5074bd712f3aba37ab53789329dce32b"
  },
  {
    "path": "assets/audio/nback/031.mp3",
    "hash": "7fadf0574a6c239596090ffe1ba1a2f4ab7415d2"
  },
  {
    "path": "assets/audio/nback/032.mp3",
    "hash": "ffa2291018e2de9e2e8508da3ec6ec7adfe67b1f"
  },
  {
    "path": "assets/audio/nback/033.mp3",
    "hash": "4cd2158b486767b18767777a94ef14cfb3e01474"
  },
  {
    "path": "assets/audio/nback/034.mp3",
    "hash": "d6d7bfe646a09a1fde1ddfc1ad0a725be9901c9a"
  },
  {
    "path": "assets/audio/nback/035.mp3",
    "hash": "5e29f6fda47e4a350633114ab42a8a73e2795195"
  },
  {
    "path": "assets/audio/nback/036.mp3",
    "hash": "5c1056bca7fe45f76618e76a9f839d0bd10a31c7"
  },
  {
    "path": "assets/audio/nback/037.mp3",
    "hash": "b4bdca602e2b2fe181e50107e413641847fbbc9f"
  },
  {
    "path": "assets/audio/nback/038.mp3",
    "hash": "5fb8f5f3aeca926c3ad1a6d5314646ad851ba26d"
  },
  {
    "path": "assets/audio/nback/039.mp3",
    "hash": "57e95634885bf14336806020f1022bcb30e59d3b"
  },
  {
    "path": "assets/audio/nback/040.mp3",
    "hash": "d69e1369b26d357a1378704c12975d8248e24693"
  },
  {
    "path": "assets/audio/nback/041.mp3",
    "hash": "a4ff3f66cb22b50c211dc4bf0bf69fcfd7e04ff0"
  },
  {
    "path": "assets/audio/nback/042.mp3",
    "hash": "b2f4c22707d6d92f991d259a485c6bfebe1ffd52"
  },
  {
    "path": "assets/audio/nback/043.mp3",
    "hash": "b5f110944a23a4a78cdb2bffffd5a9349a0eb593"
  },
  {
    "path": "assets/audio/nback/044.mp3",
    "hash": "18785f3815b5c6d296f76b375eccd745490175e4"
  },
  {
    "path": "assets/audio/nback/045.mp3",
    "hash": "723f5da00c891ac9de24843f6d9154da08ad7522"
  },
  {
    "path": "assets/audio/nback/046.mp3",
    "hash": "74f27e4358b969edbf4e01f10215a26617d7a1b8"
  },
  {
    "path": "assets/audio/nback/047.mp3",
    "hash": "c1be161ba7fd02f5df1faf063dd7fb48d38764be"
  },
  {
    "path": "assets/audio/nback/048.mp3",
    "hash": "a42e56738f787cf5819f7175d382622b95fd26f5"
  },
  {
    "path": "assets/audio/nback/049.mp3",
    "hash": "594b277e1a334709a46d2afb962d905c5dd7b1fe"
  },
  {
    "path": "assets/audio/nback/050.mp3",
    "hash": "8f774d18dfb6e6901644a84465c187d3a01e2d68"
  },
  {
    "path": "assets/audio/nback/051.mp3",
    "hash": "cecb9d6423828a4de7bceb7a8cccfe96045c46e2"
  },
  {
    "path": "assets/audio/nback/052.mp3",
    "hash": "870aa9096ade6e8621b7496f3945e8fb03521703"
  },
  {
    "path": "assets/audio/nback/053.mp3",
    "hash": "f150b3a166191c4d2f3f18fcbcda632060984617"
  },
  {
    "path": "assets/audio/nback/054.mp3",
    "hash": "512252e66d0436bf9188e9f3bf80657c6a7176da"
  },
  {
    "path": "assets/audio/nback/055.mp3",
    "hash": "de9dd8fd94b867433655574728be69d79d359253"
  },
  {
    "path": "assets/audio/nback/056.mp3",
    "hash": "4c1ca7dc5467d6f2a9ba28f24740cd3b7939a0b9"
  },
  {
    "path": "assets/audio/nback/057.mp3",
    "hash": "e77321b8c3bfb0321447166ebb533473a4bfc05e"
  },
  {
    "path": "assets/audio/nback/058.mp3",
    "hash": "7037eb8e044a08f1b546eab62b829b5b2bb95a71"
  },
  {
    "path": "assets/audio/nback/059.mp3",
    "hash": "92f1706f0e914e95e6c0b6af324a147fe619007a"
  },
  {
    "path": "assets/audio/nback/060.mp3",
    "hash": "ac536f0f00c6ca489922b9731ff884665c40910a"
  },
  {
    "path": "assets/audio/nback/061.mp3",
    "hash": "a31cc64b0783ee402c759a08933188934b859cd1"
  },
  {
    "path": "assets/audio/nback/062.mp3",
    "hash": "d88492a3cbcdb1883961bc6b3a0dc47061e949e7"
  },
  {
    "path": "assets/audio/nback/063.mp3",
    "hash": "132b235f53cea298331751b48d7fdbbb5cb43454"
  },
  {
    "path": "assets/audio/nback/064.mp3",
    "hash": "eb4252569efa2a992337bd4e7190bc23af40880a"
  },
  {
    "path": "assets/audio/nback/065.mp3",
    "hash": "c80c6fdffa1cba6dd5081c043cecdc60b39533b6"
  },
  {
    "path": "assets/audio/nback/066.mp3",
    "hash": "ec218f0f08200c1856b4ce393738a7f67ba6eccb"
  },
  {
    "path": "assets/audio/nback/067.mp3",
    "hash": "0931611d9d8b1b8c891faf0d174e080c9787d842"
  },
  {
    "path": "assets/audio/nback/068.mp3",
    "hash": "4c3f789a8487d7b09889000235d19fa2b6bc264c"
  },
  {
    "path": "assets/audio/nback/069.mp3",
    "hash": "d85de347420249be057e125af2f08d67c2fe5854"
  },
  {
    "path": "assets/audio/nback/070.mp3",
    "hash": "78a182ebb1a1c6fedbab630dd9fe98aeee5753b4"
  },
  {
    "path": "assets/audio/nback/071.mp3",
    "hash": "f8c2bd2ee05dfedef44f605da230345ee0cbd5ba"
  },
  {
    "path": "assets/audio/nback/072.mp3",
    "hash": "329edc8d6485d9bf8fe60899c1a5b2224c084529"
  },
  {
    "path": "assets/audio/nback/073.mp3",
    "hash": "88c17c1925b79095da65e0c554d4b2f49d96ab10"
  },
  {
    "path": "assets/audio/nback/074.mp3",
    "hash": "006d3abe495ca5bae976dc6338b94eec8a16b4dc"
  },
  {
    "path": "assets/audio/nback/075.mp3",
    "hash": "f49e8f52a3ba6c640b0a5e9f471da59816845da2"
  },
  {
    "path": "assets/audio/nback/076.mp3",
    "hash": "f606f11ffaf9bb858d18a2e0d8afd2fd75c1e770"
  },
  {
    "path": "assets/audio/nback/077.mp3",
    "hash": "3470be58989d12006b50c34485f62223ec6ad3e5"
  },
  {
    "path": "assets/audio/nback/078.mp3",
    "hash": "84d96c5af12694c8812a526e691382000be9e9db"
  },
  {
    "path": "assets/audio/nback/079.mp3",
    "hash": "e7cd9e1872028abe6bc8f542cff928d80b655e27"
  },
  {
    "path": "assets/audio/nback/080.mp3",
    "hash": "66b370fae3dc9be0fe412c6372af83174b11e8ee"
  },
  {
    "path": "assets/audio/nback/081.mp3",
    "hash": "e8ae59b678c27b34d16af98cea87d24756747400"
  },
  {
    "path": "assets/audio/nback/082.mp3",
    "hash": "456d14d2600bc26405ac4d9f7f71aa11465bdde1"
  },
  {
    "path": "assets/audio/nback/083.mp3",
    "hash": "5ba026e017e6c630d933c33daae65c1a293b0256"
  },
  {
    "path": "assets/audio/nback/084.mp3",
    "hash": "c06d9b079493a36a0a9c951332cb862f0d92adaf"
  },
  {
    "path": "assets/audio/nback/085.mp3",
    "hash": "12b97ae33dd6c3b7257c28e38e7bfb4706a2d027"
  },
  {
    "path": "assets/audio/nback/086.mp3",
    "hash": "90390e17db325f18797ba2163ec53651eb35480e"
  },
  {
    "path": "assets/audio/nback/087.mp3",
    "hash": "f3acf1b40a9a0ce2ceb87f074b11cb8004d33ab5"
  },
  {
    "path": "assets/audio/nback/088.mp3",
    "hash": "fed6eed798a0573bbc15c2c45fb0cb51017ea8ab"
  },
  {
    "path": "assets/audio/nback/089.mp3",
    "hash": "e4839c7e3988373b45831708922fa66fd63e0d4d"
  },
  {
    "path": "assets/audio/nback/090.mp3",
    "hash": "72ae41523ef1403d520b884deef1732c0232a1c8"
  },
  {
    "path": "assets/audio/nback/091.mp3",
    "hash": "8e49289184f513f50efb4d54898c5b7ec6bc5a69"
  },
  {
    "path": "assets/audio/nback/092.mp3",
    "hash": "202eff00c3e2bf426632e547c08e4ec839c8fe55"
  },
  {
    "path": "assets/audio/nback/093.mp3",
    "hash": "1fb3ab2a6181c49026b500a48ba985a69f1bb536"
  },
  {
    "path": "assets/audio/nback/094.mp3",
    "hash": "d4152b84e08579f3a9f8665227dc9a3be883b272"
  },
  {
    "path": "assets/audio/nback/095.mp3",
    "hash": "75764fe2174ac346c4082849bc9e2e98ace8d6b1"
  },
  {
    "path": "assets/audio/nback/096.mp3",
    "hash": "49fcaac4aa9c3b5dedbae5777086ce0fb2326616"
  },
  {
    "path": "assets/audio/nback/097.mp3",
    "hash": "c53d631762c7bcc98d3a450a8a79660dcf76e03f"
  },
  {
    "path": "assets/audio/nback/098.mp3",
    "hash": "549dc1b0b218fb24ab6dfec01ad1db48d7a63a98"
  },
  {
    "path": "assets/audio/nback/099.mp3",
    "hash": "59d1afe855f775ce08a605455079b760bfd1ca66"
  },
  {
    "path": "assets/audio/nback/100.mp3",
    "hash": "1f801732e197c9cba2313930f7ab58969efabcb8"
  },
  {
    "path": "assets/audio/nback/101.mp3",
    "hash": "3cbc11a27c9941ed9c9675443665ebcd1750dcbc"
  },
  {
    "path": "assets/audio/nback/102.mp3",
    "hash": "bdeb99f39e150f8d7356cf8c6f7f91147ce7513d"
  },
  {
    "path": "assets/audio/nback/103.mp3",
    "hash": "ddb3c42683f8f0cdbbe4a34c173af64cb94a88b0"
  },
  {
    "path": "assets/audio/nback/104.mp3",
    "hash": "26e24adea31de761f1a34dc72214aa1156461176"
  },
  {
    "path": "assets/audio/nback/105.mp3",
    "hash": "cc98d2a77638e689dcd97776af0ed2857bcd40a8"
  },
  {
    "path": "assets/audio/nback/106.mp3",
    "hash": "83c6e782d4b884d47ac1a82578e6759616fb8b27"
  },
  {
    "path": "assets/audio/nback/107.mp3",
    "hash": "7912635ea8d24e221192940fefe4e458689c73de"
  },
  {
    "path": "assets/audio/nback/108.mp3",
    "hash": "5439edd11a2c393e81a623ff88b050a92a1960c7"
  },
  {
    "path": "assets/audio/nback/109.mp3",
    "hash": "dd818bc4d39c03ded7679d35ed23882aa6ec1a58"
  },
  {
    "path": "assets/audio/nback/110.mp3",
    "hash": "3984ed5b0765cef43ca0cb2adc2424cd866e516b"
  },
  {
    "path": "assets/audio/nback/111.mp3",
    "hash": "54ee2a9973abf378d122962ae0ea0d1cb1b74ba8"
  },
  {
    "path": "assets/audio/nback/112.mp3",
    "hash": "44c8e1cb983db078bc1d46c1aef6bd516d24e1ce"
  },
  {
    "path": "assets/audio/nback/113.mp3",
    "hash": "400a526815322532b97ab3f318039696b181f8c7"
  },
  {
    "path": "assets/audio/nback/114.mp3",
    "hash": "adeeab2af90171b2fd47b78291e7c012e70b9857"
  },
  {
    "path": "assets/audio/nback/115.mp3",
    "hash": "b99abe965907e694e91986ce005a4200e4b2a896"
  },
  {
    "path": "assets/audio/nback/116.mp3",
    "hash": "a93cdae714b71839ad878c8289ef6a1c4bf52268"
  },
  {
    "path": "assets/audio/nback/117.mp3",
    "hash": "f3345d82b2fc64d940cda6f61fd0b40c4c0c5d93"
  },
  {
    "path": "assets/audio/nback/118.mp3",
    "hash": "1c1d90271d93e878253d29386757d26f2e366820"
  },
  {
    "path": "assets/audio/nback/119.mp3",
    "hash": "8bcbe51fb49e4d37e8e118bb03dc969f18e024cc"
  },
  {
    "path": "assets/audio/nback/120.mp3",
    "hash": "1a60b10625a0c7872511f5eae1e5fd733603e6df"
  },
  {
    "path": "assets/audio/nback/121.mp3",
    "hash": "ace9019505a3f87bc032d47825d6531d628221ed"
  },
  {
    "path": "assets/audio/nback/122.mp3",
    "hash": "da6e7342842b1b466acc47ca145e0ea885047153"
  },
  {
    "path": "assets/audio/nback/123.mp3",
    "hash": "f57af4e844c2c7e9a383286d6b0abcd8f4bdaa7b"
  },
  {
    "path": "assets/audio/nback/124.mp3",
    "hash": "d5f529468898c7d065ec1f1fb8020ecd1fd5fac6"
  },
  {
    "path": "assets/audio/nback/125.mp3",
    "hash": "1a09984ae9d468037191a788733a9af9577242d3"
  },
  {
    "path": "assets/audio/nback/126.mp3",
    "hash": "75f70bd6a6dd826daf9167710aa6a209fd9da0d5"
  },
  {
    "path": "assets/audio/nback/127.mp3",
    "hash": "5d8d5acf62bb623e267cdc1f36afe3f100ba149c"
  },
  {
    "path": "assets/audio/nback/128.mp3",
    "hash": "bfd23cce1a9ce041dbaad42cdaeabdeb4aee585c"
  },
  {
    "path": "assets/audio/nback/129.mp3",
    "hash": "55a469d8ebe304404d09ac2baa7336112df9ed06"
  },
  {
    "path": "assets/audio/nback/130.mp3",
    "hash": "7e9f4c5a8f79548d5f4b8de75837f38620304d07"
  },
  {
    "path": "assets/audio/nback/131.mp3",
    "hash": "3272fe3188a8858939b3b9ca64bef7fece4b8053"
  },
  {
    "path": "assets/audio/nback/132.mp3",
    "hash": "6880a424bedab8d6b94aff442fbae18d1f1a6254"
  },
  {
    "path": "assets/audio/nback/133.mp3",
    "hash": "55887a69f003af24e8b14e3300ebafcb712d3f86"
  },
  {
    "path": "assets/audio/nback/134.mp3",
    "hash": "d4163773bdc0f106b38fe37d0bf61916f1f31bac"
  },
  {
    "path": "assets/audio/nback/135.mp3",
    "hash": "23a2795cc4ec8b625087ac08b2c1aafa201af793"
  },
  {
    "path": "assets/audio/nback/136.mp3",
    "hash": "a5f6dd6ca74fd5c0a3d42f40a0af2cd09da8270e"
  },
  {
    "path": "assets/audio/nback/137.mp3",
    "hash": "307840486ddf2d0850734c07ebac884dd3661780"
  },
  {
    "path": "assets/audio/nback/138.mp3",
    "hash": "9cac334973f1fae1a93585d7a2770b75a6459608"
  },
  {
    "path": "assets/audio/nback/139.mp3",
    "hash": "e41b261738e47d9c7e6c097f6d8753dc828d36f9"
  },
  {
    "path": "assets/audio/nback/140.mp3",
    "hash": "e676c8c7f59c52451eec4cb19b45434922c0fa5d"
  },
  {
    "path": "assets/audio/nback/141.mp3",
    "hash": "40560c86740f41d625ff8110113e299726636e81"
  },
  {
    "path": "assets/audio/nback/142.mp3",
    "hash": "0f681d70c121fce516cb1d6c52dc8703960895db"
  },
  {
    "path": "assets/audio/nback/143.mp3",
    "hash": "eb09ac9fa8d174bcee42b63a87cef64f1413aff0"
  },
  {
    "path": "assets/audio/nback/144.mp3",
    "hash": "cf4c90dd9fd4f83b493dabae335b1ca3455937ea"
  },
  {
    "path": "assets/audio/nback/145.mp3",
    "hash": "15832416ae97a910228587663d9180414fa0d9c2"
  },
  {
    "path": "assets/audio/nback/146.mp3",
    "hash": "e9bf65f21b4481eae4bf25468502153c75b4d09a"
  },
  {
    "path": "assets/audio/nback/147.mp3",
    "hash": "f2564dc082d5e42a9eb2767a64f13944b1e86c79"
  },
  {
    "path": "assets/audio/nback/148.mp3",
    "hash": "837d9906218f7680241a6be0c06a3cc8d8ee78bd"
  },
  {
    "path": "assets/audio/nback/149.mp3",
    "hash": "aca86c8595f6ed63b2833f9f2f9da19c0275b049"
  },
  {
    "path": "assets/audio/nback/150.mp3",
    "hash": "531428392e83bfefc2036d6ddc35934f2886f2f7"
  },
  {
    "path": "assets/audio/nback/151.mp3",
    "hash": "e3115bf21950584f156dcf4acf162976ec261587"
  },
  {
    "path": "assets/audio/nback/152.mp3",
    "hash": "28f1964b0a66beee66cb2976ab0e298375448537"
  },
  {
    "path": "assets/audio/nback/153.mp3",
    "hash": "b689fb7f75577ceab13d30f4dbf043bbf944c9bd"
  },
  {
    "path": "assets/audio/nback/154.mp3",
    "hash": "546126fdcd4256cb0d4b3aa33e0220575af30ff5"
  },
  {
    "path": "assets/audio/nback/155.mp3",
    "hash": "07d8d47d0406f1a95a8f090f9287b61755b890a3"
  },
  {
    "path": "assets/audio/nback/156.mp3",
    "hash": "07312c1f2088c068974039e8d6253c4390384617"
  },
  {
    "path": "assets/audio/nback/157.mp3",
    "hash": "30f7f39a3433598130b7df62e96d7dcd74a44e88"
  },
  {
    "path": "assets/audio/nback/158.mp3",
    "hash": "018b16cb47cb51c7e52e5f7402cd7646e5cc6acd"
  },
  {
    "path": "assets/audio/nback/159.mp3",
    "hash": "86a70827b266da74254adbe62969beeb9b5590f7"
  },
  {
    "path": "assets/audio/nback/160.mp3",
    "hash": "f6a22d61a6432016a06983c9de37df71c5e5b0ac"
  },
  {
    "path": "assets/celebrity-faces/anita-mui_canonical.webp",
    "hash": "67152b28ee02d94593f9231d25746e734dafed1c"
  },
  {
    "path": "assets/celebrity-faces/anita-mui_happy.webp",
    "hash": "af5d809b6a056ae033069e84adfad279c70626bd"
  },
  {
    "path": "assets/celebrity-faces/anita-mui_sad.webp",
    "hash": "64df4501e7bec6407e8505a7d3afa2c9278c9a23"
  },
  {
    "path": "assets/celebrity-faces/bruce-lee_canonical.webp",
    "hash": "fcf38a8d7506e17dac18002d3fc5472f66dd97c7"
  },
  {
    "path": "assets/celebrity-faces/bruce-lee_happy.webp",
    "hash": "c7a05d3afd99a20f32dc37b63d3530ea2e2ee4f0"
  },
  {
    "path": "assets/celebrity-faces/bruce-lee_sad.webp",
    "hash": "e571b611a18a49eac47af4be670e4e762008660e"
  },
  {
    "path": "assets/celebrity-faces/chow-yun-fat_canonical.webp",
    "hash": "0b43bbbd21b27fe34b4189bfead5849f607d413d"
  },
  {
    "path": "assets/celebrity-faces/chow-yun-fat_happy.webp",
    "hash": "c11fb23f7f0cbc5910aa3c2dccd754f9f39871bf"
  },
  {
    "path": "assets/celebrity-faces/chow-yun-fat_sad.webp",
    "hash": "6fabce58dfd2c91f86a8f6c8646db8edf83817ba"
  },
  {
    "path": "assets/celebrity-faces/leslie-cheung_canonical.webp",
    "hash": "501048737b9266a4d02477430ddf22ed3d555b0e"
  },
  {
    "path": "assets/celebrity-faces/leslie-cheung_happy.webp",
    "hash": "3c7da6fdf4b7fe5e4ce41b1a0b67dc1e233c4321"
  },
  {
    "path": "assets/celebrity-faces/leslie-cheung_sad.webp",
    "hash": "7c9536618cadf3317ad2019ed2ae8be7e63a8db6"
  },
  {
    "path": "assets/celebrity-faces/leung-sing-bor_canonical.webp",
    "hash": "a6063615562e078c2ee9cbedf47df3fc63973a63"
  },
  {
    "path": "assets/celebrity-faces/leung-sing-bor_happy.webp",
    "hash": "627a8a6f925ef783c314eae45134a1c28ac4ae20"
  },
  {
    "path": "assets/celebrity-faces/leung-sing-bor_sad.webp",
    "hash": "3d8d6afec90b1eb2966f9c5546f9cc06da104350"
  },
  {
    "path": "assets/celebrity-faces/liza-wang_canonical.webp",
    "hash": "675e552460d25640db62197a88792365c3b4fb50"
  },
  {
    "path": "assets/celebrity-faces/liza-wang_happy.webp",
    "hash": "1a68458ec3fafacf54172ee1a3ed0fbaed241356"
  },
  {
    "path": "assets/celebrity-faces/liza-wang_sad.webp",
    "hash": "0448c483860de394622e2dc0d1bf314b270c1a49"
  },
  {
    "path": "assets/celebrity-faces/paula-tsui_canonical.webp",
    "hash": "30905a2cbeefb44e099903b56dbb91cef4135942"
  },
  {
    "path": "assets/celebrity-faces/paula-tsui_happy.webp",
    "hash": "2569903046c28dfedc4464ac95130078b3dcc470"
  },
  {
    "path": "assets/celebrity-faces/paula-tsui_sad.webp",
    "hash": "13bfa35e750ae55640236756269566c57d86505e"
  },
  {
    "path": "assets/celebrity-faces/sam-hui_canonical.webp",
    "hash": "336578f150a5d22872f3310a42fd4d24b6efabcf"
  },
  {
    "path": "assets/celebrity-faces/sam-hui_happy.webp",
    "hash": "a95ef041fba8ae29d3d75277e71dcf8afc8e7169"
  },
  {
    "path": "assets/celebrity-faces/sam-hui_sad.webp",
    "hash": "988c2436457419f7215a71ebad6455aae65f6556"
  },
  {
    "path": "assets/celebrity-faces/teresa-teng_canonical.webp",
    "hash": "aa75855b751e051d17f66d41911171886135105f"
  },
  {
    "path": "assets/celebrity-faces/teresa-teng_happy.webp",
    "hash": "7ff49c22537be1311a9ebaa3ae189523d65e5b7c"
  },
  {
    "path": "assets/celebrity-faces/teresa-teng_sad.webp",
    "hash": "12c9638e10514b36125d704ad9bf0b5414cda93f"
  },
  {
    "path": "assets/celebrity-faces/yam-kim-fai_canonical.webp",
    "hash": "d5b07c2599a9b3a8426a9d8404229348be6617b7"
  },
  {
    "path": "assets/celebrity-faces/yam-kim-fai_happy.webp",
    "hash": "d928ba6df3473c8556f61599f19b1d79a85d53b3"
  },
  {
    "path": "assets/celebrity-faces/yam-kim-fai_sad.webp",
    "hash": "1f73b6007cf465039ad10fa81dfa956ba3e1c5bc"
  },
  {
    "path": "assets/food/乳鴿.webp",
    "hash": "55caf80199f2d0162e95c9ce76b696419d2fcf3c"
  },
  {
    "path": "assets/food/八爪魚.webp",
    "hash": "d0a84307db1288239bf38fe6640fb90d1358348e"
  },
  {
    "path": "assets/food/冬瓜.webp",
    "hash": "d359242b474c2ea95a0da0a628918222d4b19f83"
  },
  {
    "path": "assets/food/冬甩.webp",
    "hash": "5e201fbd5b8aae63c3ee92c66c0459dd527c7b95"
  },
  {
    "path": "assets/food/冬菇.webp",
    "hash": "9acfd1be58ac4871096c7254b11ac5ddc732123c"
  },
  {
    "path": "assets/food/午餐肉.webp",
    "hash": "c3acd87d34b859fb532944bf237aea6abe9d4b5d"
  },
  {
    "path": "assets/food/南瓜.webp",
    "hash": "6406f1cd095cea705a8c08501d48b6ddedb1a2e3"
  },
  {
    "path": "assets/food/叉燒.webp",
    "hash": "f0b9480833e0f6f0916b734796a06af01e52a727"
  },
  {
    "path": "assets/food/叉燒包.webp",
    "hash": "f7a402971de4b0a9c8da03cab9046784d386027a"
  },
  {
    "path": "assets/food/吞拿魚.webp",
    "hash": "25faa059ad1f84c7afa80ac1cc6bdf27fcd5cb03"
  },
  {
    "path": "assets/food/咕嚕肉.webp",
    "hash": "02a3b03e6898810d92416106f683dc485a66eec9"
  },
  {
    "path": "assets/food/咸水角.webp",
    "hash": "facce1beb4a5e6899dd533006b87678aae9ab9cb"
  },
  {
    "path": "assets/food/四季豆.webp",
    "hash": "0b6d472ddfb7291988aff7e8646efbfd29451067"
  },
  {
    "path": "assets/food/墨魚.webp",
    "hash": "df40165974613237326f9eaeff1486858553e5e6"
  },
  {
    "path": "assets/food/大樹菠蘿.webp",
    "hash": "fec7fc4f5f6aa1e849637929a702b395a2139f59"
  },
  {
    "path": "assets/food/奇異果.webp",
    "hash": "b9500c2bd5d94811ae16152dd76d05b1b9a3a73d"
  },
  {
    "path": "assets/food/姜.webp",
    "hash": "557ec4224aecd389382e2a2619d7df3909ca2e84"
  },
  {
    "path": "assets/food/娃娃菜.webp",
    "hash": "ca63d58659fa9e000a006732ee338d0c91f1a8ae"
  },
  {
    "path": "assets/food/小籠包.webp",
    "hash": "d5960bd39208d30709e282ed8bd01c114705582c"
  },
  {
    "path": "assets/food/山竹.webp",
    "hash": "a6de352e48f3e2e363da48ec37b3bf60f24544c4"
  },
  {
    "path": "assets/food/山竹牛肉球.webp",
    "hash": "49034f9bd535c83aed06f50ceb6413b729bea8fb"
  },
  {
    "path": "assets/food/巧克力.webp",
    "hash": "16847ee6929b0fe9ccb00fa2591671fc051a2fe0"
  },
  {
    "path": "assets/food/帶子.webp",
    "hash": "97bb8c39fdcea3f7b00f3bef929abcd380b8e100"
  },
  {
    "path": "assets/food/春卷.webp",
    "hash": "7ff3db0b38311394ec23fa26e787bc31f871f427"
  },
  {
    "path": "assets/food/曲奇.webp",
    "hash": "934d65ef6c67217949b08c2a1ec608ec43d4f1b9"
  },
  {
    "path": "assets/food/月餅.webp",
    "hash": "4962eec8784555c81c10a487ad9dcf73cb914e04"
  },
  {
    "path": "assets/food/木瓜.webp",
    "hash": "ac85d3f9ba74e896009d550b17c7659dd75e0f8e"
  },
  {
    "path": "assets/food/木耳.webp",
    "hash": "01c9261a45c263bdf318345b2a7a8ed688f73178"
  },
  {
    "path": "assets/food/杏仁.webp",
    "hash": "b5c2958ecf54c653c5060d464240904326adbc23"
  },
  {
    "path": "assets/food/杏仁餅.webp",
    "hash": "adddcedfa6baed10fb0f1f27789a787dc2b968b7"
  },
  {
    "path": "assets/food/東坡肉.webp",
    "hash": "fce67568b4ac9c0f8dd1f2fd50dc133e597d2a03"
  },
  {
    "path": "assets/food/枇杷.webp",
    "hash": "aef69ccb773d38c51119d0a229879426245473e5"
  },
  {
    "path": "assets/food/柑.webp",
    "hash": "6ca58859beece5be3716b95bd72a39541eefd62d"
  },
  {
    "path": "assets/food/柿子.webp",
    "hash": "ce3ac4e1dd9d16f6b5ea4d987e5f94254bf78c22"
  },
  {
    "path": "assets/food/栗子.webp",
    "hash": "e13d0786a98eb923f8bc9db6ddb535546e9239b0"
  },
  {
    "path": "assets/food/核桃.webp",
    "hash": "cbbced2ea46fcff85760b330716693adc2bd2de5"
  },
  {
    "path": "assets/food/格仔餅.webp",
    "hash": "112cca0d44867d60f14768e26d530c3114616400"
  },
  {
    "path": "assets/food/桂花糕.webp",
    "hash": "c28833f94c1cea29d3e82b46a3efd86d6264bc9d"
  },
  {
    "path": "assets/food/桃子.webp",
    "hash": "390250de0cd44925e6f04a0ae13311728839d3ff"
  },
  {
    "path": "assets/food/桑椹.webp",
    "hash": "6b1675098bee9c7ce190aa8fccb345ea51b7a03d"
  },
  {
    "path": "assets/food/梨.webp",
    "hash": "00acdefd1afd0f8497bb368ac9045c55d9d9c92e"
  },
  {
    "path": "assets/food/椰子.webp",
    "hash": "ff5410f358b80dd1eceb0651404ea72f0fa7b20c"
  },
  {
    "path": "assets/food/椰菜.webp",
    "hash": "c668e6b3e01ba21122c563e7055df7a46aa72b66"
  },
  {
    "path": "assets/food/楊枝甘露.webp",
    "hash": "81dc9982ec15fa531181568cc5c6b1bc9f6f5a29"
  },
  {
    "path": "assets/food/楊桃.webp",
    "hash": "eb8d7cff654c00185950219bb33813cb0d12fec2"
  },
  {
    "path": "assets/food/榛子.webp",
    "hash": "94f6c20ae461e179220ac865f8f332afd67cd103"
  },
  {
    "path": "assets/food/榴蓮.webp",
    "hash": "36c264ad5f31c5305ad99253cddf02b04a67c29a"
  },
  {
    "path": "assets/food/橙子.webp",
    "hash": "0e805be485753a69ff12ec31187daec5ef5cbf94"
  },
  {
    "path": "assets/food/檸檬.webp",
    "hash": "ccb29cc9321076cc6a425c86f971b8aa660b68d3"
  },
  {
    "path": "assets/food/櫻桃.webp",
    "hash": "07e4b3da830fea94cefe78d83843df0cca7e7eaf"
  },
  {
    "path": "assets/food/比目魚.webp",
    "hash": "c2f4d2e1beec3163ae37d5f5150c8cabaefe2a47"
  },
  {
    "path": "assets/food/洋蔥.webp",
    "hash": "93624e0963877bc3c1147b9e9c98d471ff7079ff"
  },
  {
    "path": "assets/food/流沙包.webp",
    "hash": "fd92033ee6c23130878a0273d85977be55a682c7"
  },
  {
    "path": "assets/food/海參.webp",
    "hash": "f4a13460aa9841b97ab9c5e1f9ae1fa4fdb91232"
  },
  {
    "path": "assets/food/海膽.webp",
    "hash": "1f35c792c5db03d6ac67f60b251e2cf35421171b"
  },
  {
    "path": "assets/food/涼瓜.webp",
    "hash": "a4912f1172976eaf8eae9ed54c7e1f8491c4bb0a"
  },
  {
    "path": "assets/food/涼粉.webp",
    "hash": "773a37319c12a1ae201cce20073299981eab677b"
  },
  {
    "path": "assets/food/湯圓.webp",
    "hash": "24138dd00f36dce2b2b23d5b218c378e8fb54b43"
  },
  {
    "path": "assets/food/火龍果.webp",
    "hash": "228e7a0e404a15ae20b9a6f8ed3eb711a3eb37f1"
  },
  {
    "path": "assets/food/炒蜆.webp",
    "hash": "12e1aaabe2bac67374bf15ac569d47ea13abbaef"
  },
  {
    "path": "assets/food/烤鴨.webp",
    "hash": "41c1b16751cbedeb573990dfb3bb6e76b96c1878"
  },
  {
    "path": "assets/food/燒肉.webp",
    "hash": "0ff66c1371fd468dcb0a60fdbc2ce200dd228655"
  },
  {
    "path": "assets/food/燒賣.webp",
    "hash": "fb417acae9fbd57a265796ad5a53444e5193080e"
  },
  {
    "path": "assets/food/燕麥.webp",
    "hash": "90bec30ec6e092572d85ac438242fd234c06a95e"
  },
  {
    "path": "assets/food/牛丸.webp",
    "hash": "b5cf7ed07452ba49274982e0d09a97afabfba217"
  },
  {
    "path": "assets/food/牛扒.webp",
    "hash": "291024d1fd92874a5e84c791c4ad737299478606"
  },
  {
    "path": "assets/food/牛柏葉.webp",
    "hash": "7d00c7e25cc30fe4fabc35afb87833e356b3405f"
  },
  {
    "path": "assets/food/牛蒡.webp",
    "hash": "0cc897355fd4bfe7db17cf2ea1959dee18df0ce0"
  },
  {
    "path": "assets/food/玉米.webp",
    "hash": "edb3703c6023a86d2b9fa1bf6bbaa742820c2ded"
  },
  {
    "path": "assets/food/瓜子.webp",
    "hash": "2cfb44413397c472e00b2189690e16ce32c6a1ed"
  },
  {
    "path": "assets/food/生蠔.webp",
    "hash": "4c91161674b97ad4ae32d5a28d30a436453622ed"
  },
  {
    "path": "assets/food/番石榴.webp",
    "hash": "ad884bff1301ce4e6cf6867aefe1906ed355f2d4"
  },
  {
    "path": "assets/food/番茄.webp",
    "hash": "6994126fe9e78b45757f7f00170e78610a4153ba"
  },
  {
    "path": "assets/food/番薯糖水.webp",
    "hash": "170b1a73e1dcad9af5e1e56e0acdbd5887517c4c"
  },
  {
    "path": "assets/food/白切雞.webp",
    "hash": "a160794b2caa78fbdea9262ca5e715f222216c71"
  },
  {
    "path": "assets/food/白糖糕.webp",
    "hash": "69595dbf4d00d253843ac04aeedf0f536479be6f"
  },
  {
    "path": "assets/food/白菜.webp",
    "hash": "eed09f0c6ed56eba08f3d8181799da2bb793ebff"
  },
  {
    "path": "assets/food/白蘿蔔.webp",
    "hash": "3471d31c45f7a565d298727434aefdff6950645f"
  },
  {
    "path": "assets/food/百香果.webp",
    "hash": "5275c88fd565b11599f2ef8940a4f6efa2873576"
  },
  {
    "path": "assets/food/石斑.webp",
    "hash": "11c2b7b39c21547a6a70883d1cc197f74d32dcb2"
  },
  {
    "path": "assets/food/節瓜.webp",
    "hash": "eb21f1b7776e500b6253f15b5069cfce026e4880"
  },
  {
    "path": "assets/food/米飯.webp",
    "hash": "540a330519b63edfa16673b9bde8ee5bfa8436bf"
  },
  {
    "path": "assets/food/粉粿.webp",
    "hash": "3e8a984ba18f39a5a3acdde373a9ae27d617128e"
  },
  {
    "path": "assets/food/糯米雞.webp",
    "hash": "c777632e2112459684d70727f1669012299b9b3d"
  },
  {
    "path": "assets/food/紅蘿蔔.webp",
    "hash": "b068a215459ac477f36d33c3ba9136d48c25303e"
  },
  {
    "path": "assets/food/紅衫魚.webp",
    "hash": "5522008f6af34fcb0ace505974cc7895584228f9"
  },
  {
    "path": "assets/food/紅豆沙.webp",
    "hash": "30032a4ab238f6aade8851f23a43d5f3637c6eef"
  },
  {
    "path": "assets/food/綠豆沙.webp",
    "hash": "c6ebda279617358195d5fb97082324e0ddced2de"
  },
  {
    "path": "assets/food/綠豆餅.webp",
    "hash": "085c34aae0fea9d249d0d174ac47c4c6175fd604"
  },
  {
    "path": "assets/food/缽仔糕.webp",
    "hash": "d13cd111d67283855478610794d67f119971e6fb"
  },
  {
    "path": "assets/food/腰果.webp",
    "hash": "8b5105a6f624ec9789171c58cf3d342fdde5cbd5"
  },
  {
    "path": "assets/food/腸仔.webp",
    "hash": "fbf6ab59c1e39864935c1fc6cd57df52aedd78de"
  },
  {
    "path": "assets/food/腸粉.webp",
    "hash": "86eb7a6cfc75f30e25f7c0f0b6a2d239dbcadd13"
  },
  {
    "path": "assets/food/臘腸.webp",
    "hash": "0296ddbc449e56e7fa4879d5d562845cfa1bc696"
  },
  {
    "path": "assets/food/芋頭.webp",
    "hash": "6849aac0f642aeeee017836f527dc0e44bd188f8"
  },
  {
    "path": "assets/food/芒果.webp",
    "hash": "23fd2110bbd5ee1fcb14b5b39682f8635f951ed5"
  },
  {
    "path": "assets/food/芝麻卷.webp",
    "hash": "83a444c45908ed932c772915d508dbc97ab3182b"
  },
  {
    "path": "assets/food/芝麻糊.webp",
    "hash": "7f2e685afeac33a76c01462c167a2a877036fd02"
  },
  {
    "path": "assets/food/花椰菜.webp",
    "hash": "2c13588b0f6625af57c44233d900b0b4e1e68b92"
  },
  {
    "path": "assets/food/花生.webp",
    "hash": "ff9f5c9803ac164a74e697fa86b99ef243a51e0f"
  },
  {
    "path": "assets/food/芹菜.webp",
    "hash": "4947382979fc4a56dfd0cdfdb1adc0e7fae881b8"
  },
  {
    "path": "assets/food/茄子.webp",
    "hash": "304bf201d067e185da5b89000ba087035758513e"
  },
  {
    "path": "assets/food/草莓.webp",
    "hash": "471cf3ebd7d2ab99f8e46b20051f237dcc5ede52"
  },
  {
    "path": "assets/food/荔枝.webp",
    "hash": "368981fb5ea411f176f0d40e7dd6258a79e8bd84"
  },
  {
    "path": "assets/food/菠蘿.webp",
    "hash": "028a1b3f4abc30d5f66020ea28238f63c92e0a6a"
  },
  {
    "path": "assets/food/葡萄.webp",
    "hash": "14f60c302ec6f5d8f578c97a65d46b6c00a8fa0d"
  },
  {
    "path": "assets/food/蒜頭.webp",
    "hash": "d966f38115a6960c293305c0b65c0a1a212003e8"
  },
  {
    "path": "assets/food/蓮藕.webp",
    "hash": "906b3570ea77666c7ac8b1fd66fa2cc8f015b425"
  },
  {
    "path": "assets/food/蔥.webp",
    "hash": "0478b3d7ed33c9d338e5d5f69a523ef7d1b7f01d"
  },
  {
    "path": "assets/food/藍莓.webp",
    "hash": "dfd2665ab0e868317eb028f0d236f90af95cfc93"
  },
  {
    "path": "assets/food/蘋果.webp",
    "hash": "3f39a9741ddd0a5f8f04ddbbf26dd2bfa67c1308"
  },
  {
    "path": "assets/food/蘑菇.webp",
    "hash": "db1d4a551e19d3a475ca156a17e21339c3053807"
  },
  {
    "path": "assets/food/蘿蔔糕.webp",
    "hash": "653461f527739975c4635bbbe378de0c581be242"
  },
  {
    "path": "assets/food/蛋卷.webp",
    "hash": "a305f160abdae1088d6021ef60ab47c1bb2cba02"
  },
  {
    "path": "assets/food/蛋撻.webp",
    "hash": "adcfe17dcf267829aba07eb1d655f53d9b4e51ba"
  },
  {
    "path": "assets/food/蛋散.webp",
    "hash": "a7a7eaa5946cab6e4c6458a55f655673138a83c3"
  },
  {
    "path": "assets/food/蛋糕.webp",
    "hash": "7bc892f6c7961fd0fbfa7182bd6605ca378307ab"
  },
  {
    "path": "assets/food/蝦.webp",
    "hash": "3eabaff04bd3c34534af513e64274ea9eb88de0c"
  },
  {
    "path": "assets/food/蝦餃.webp",
    "hash": "1d2e7b506768cafc706a7f80a0ecf49dfdade8ef"
  },
  {
    "path": "assets/food/螃蟹.webp",
    "hash": "fa6a3403d6cad51f0abe211c84143fde86843ff8"
  },
  {
    "path": "assets/food/蟶子.webp",
    "hash": "435d92252a837fb89ae78cb90b28ed08176f9824"
  },
  {
    "path": "assets/food/西洋菜.webp",
    "hash": "7613739d6057a50cc8c7f4e318648b26d5fb3302"
  },
  {
    "path": "assets/food/西瓜.webp",
    "hash": "ec47e32e4b38b11a1ae7bdf82827d9d027154aa9"
  },
  {
    "path": "assets/food/西生菜.webp",
    "hash": "5dcd5347a4f01273010ab607ecb3fc44e12576e4"
  },
  {
    "path": "assets/food/西蘭花.webp",
    "hash": "8b8b44b5b5ea8661c9ceb1de2af50cc26d12f80d"
  },
  {
    "path": "assets/food/豆腐花.webp",
    "hash": "134e4045b429f9c580f6d345d13c0e96be2d59fd"
  },
  {
    "path": "assets/food/豉汁排骨.webp",
    "hash": "74695e326bacfe31d069f307a4cc4bbae0b3adfd"
  },
  {
    "path": "assets/food/象拔蚌.webp",
    "hash": "1deb9e41af4a6a36fbc4a4da2ba18a15706cdea7"
  },
  {
    "path": "assets/food/豬肉.webp",
    "hash": "e0ec42324acf4fdee836eb821da7bd3227b7c473"
  },
  {
    "path": "assets/food/豬腳.webp",
    "hash": "7819596204b4195c4d3cb325b569f0ff0f822cbf"
  },
  {
    "path": "assets/food/金錢肚.webp",
    "hash": "5ae912cb8d66b7fba0b8651666bdd8fafb0fe04f"
  },
  {
    "path": "assets/food/開心果.webp",
    "hash": "83606b3e1b132f5888c713f082f305d49a11ab79"
  },
  {
    "path": "assets/food/雞扎.webp",
    "hash": "b1e0c8b8604ef7e9dd1f6c9fa3579a4f5daafbc1"
  },
  {
    "path": "assets/food/雞翼.webp",
    "hash": "e99226ab3d2064d4afa9de322fb6faf3aa463819"
  },
  {
    "path": "assets/food/雞蛋.webp",
    "hash": "ed810428d86774a8bbcf20e140fa462fdf70bd4f"
  },
  {
    "path": "assets/food/雞蛋仔.webp",
    "hash": "2958563f0652caca5e2eb2d31959fb92efd63eaf"
  },
  {
    "path": "assets/food/雞髀.webp",
    "hash": "250f554e064bd9ecb027b6ef03f0e6b3480f39a7"
  },
  {
    "path": "assets/food/雪梨.webp",
    "hash": "8080d9a8a5aa7a2d35db388738cf2ca3931059f7"
  },
  {
    "path": "assets/food/雪糕.webp",
    "hash": "0a8da2b61b887ed300a503f64ae31758e8244686"
  },
  {
    "path": "assets/food/青椒.webp",
    "hash": "b52e4720bd52c0b7bb7425a01b883db3bae8b4de"
  },
  {
    "path": "assets/food/韭菜.webp",
    "hash": "7acee8a7347b6d0ec501c687c1cd725e4498d740"
  },
  {
    "path": "assets/food/餃子.webp",
    "hash": "abfa0ff2542bf3ffe664d9838ed8dd40209ab4c5"
  },
  {
    "path": "assets/food/餅乾.webp",
    "hash": "488121d930facb7fc045d67aec1b09157ac006a7"
  },
  {
    "path": "assets/food/香蕉.webp",
    "hash": "f5a1380b3d520a5ecbc0077a8bf4d9f2794c4610"
  },
  {
    "path": "assets/food/香蕉糕.webp",
    "hash": "deb35132971a72b474012097cf22f91e5e938a97"
  },
  {
    "path": "assets/food/馬拉糕.webp",
    "hash": "970355a4ec4a1929e0c91b64c9d810a5a91f89bc"
  },
  {
    "path": "assets/food/馬鈴薯.webp",
    "hash": "7b0c5d611d170903feb07533233785e1ed1efcf6"
  },
  {
    "path": "assets/food/鮑魚.webp",
    "hash": "dd4aa3e9bb9d558ef000691d231e8ff216b028e2"
  },
  {
    "path": "assets/food/鮭魚.webp",
    "hash": "9388871d2afe68a59a34affb2599e1bc4d5e9b9c"
  },
  {
    "path": "assets/food/鱸魚.webp",
    "hash": "9fe88886346bfc7810a5619c88d39c3b289360bc"
  },
  {
    "path": "assets/food/鳳梨酥.webp",
    "hash": "c4b72ee338c8d6dbf52f1a2d7f6b8a464642dcd1"
  },
  {
    "path": "assets/food/鳳爪.webp",
    "hash": "99c10292cf97e50b9f69dbd7151961bae7e03319"
  },
  {
    "path": "assets/food/麵條.webp",
    "hash": "8ab76c2d568639c4c6da6903be8f994f18d8fb5f"
  },
  {
    "path": "assets/food/黃瓜.webp",
    "hash": "7649ced89dfc98f39d55c97c356091a8c555ff35"
  },
  {
    "path": "assets/food/黃皮.webp",
    "hash": "0ed232f765ce4d1a9c372ff51654840934919d0e"
  },
  {
    "path": "assets/food/黃立鯧.webp",
    "hash": "26c821d734f563692b4a1a1ebfc5e4b91f0bb671"
  },
  {
    "path": "assets/food/黃花魚.webp",
    "hash": "ce1982db1747a2c1a7c677ec3b5e62619ca7d794"
  },
  {
    "path": "assets/food/黑芝麻.webp",
    "hash": "ed42f0137066d443075fbd7fb16e865c3ca048db"
  },
  {
    "path": "assets/food/龍眼.webp",
    "hash": "eba35192991ee78e60834050096d1caede63180e"
  },
  {
    "path": "assets/food/龍蝦.webp",
    "hash": "ff2fe4d4d45acf95793cce7ffa6f27bc15f5e12c"
  },
  {
    "path": "assets/gestures/left/four.webp",
    "hash": "e7a8433ce0e020e25f5d3d38bc4b9435e729d447"
  },
  {
    "path": "assets/gestures/left/gun.webp",
    "hash": "00b909ce0212198c07574a15114f8d53906c51f4"
  },
  {
    "path": "assets/gestures/left/ok.webp",
    "hash": "f2a0a3f7301c274df8b19893ab8c0c6d9ed43a52"
  },
  {
    "path": "assets/gestures/left/palmar_four.webp",
    "hash": "c2cc44598f878718079fbb73a510faf5c7a40b66"
  },
  {
    "path": "assets/gestures/left/palmar_gun.webp",
    "hash": "cdb5ac735592d15a53f3b30423db2a22ef508dfc"
  },
  {
    "path": "assets/gestures/left/palmar_ok.webp",
    "hash": "654ef43cf004f464bac39559d47d5941022deff7"
  },
  {
    "path": "assets/gestures/left/palmar_paper.webp",
    "hash": "1547bdbc21fd8ef270346949fb19b49dc696b90d"
  },
  {
    "path": "assets/gestures/left/palmar_rock.webp",
    "hash": "dbd0de3b3ea9d77d881b3298d19492cc8d9fdd71"
  },
  {
    "path": "assets/gestures/left/palmar_scissors.webp",
    "hash": "141584027d0fda64058cff88ab06c8a428697965"
  },
  {
    "path": "assets/gestures/left/paper.webp",
    "hash": "00c51dfe2218d49ccb88ffec6574cceb372c801e"
  },
  {
    "path": "assets/gestures/left/rock.webp",
    "hash": "98865c58e2557397c99b785a49ed94253d227b68"
  },
  {
    "path": "assets/gestures/left/scissors.webp",
    "hash": "9de66e8269248e6abdd4b78dd55905b4a6e6ad3c"
  },
  {
    "path": "assets/gestures/left/thumbsdown.webp",
    "hash": "d58f08fdf8a97d226ad48d8e30942da72d09197d"
  },
  {
    "path": "assets/gestures/left/thumbsup.webp",
    "hash": "56623ad669b054bcd1b2b957c40149286b5b22d8"
  },
  {
    "path": "assets/gestures/right/four.webp",
    "hash": "a807b2509c31084ae51f17da0fca3b85571e7306"
  },
  {
    "path": "assets/gestures/right/gun.webp",
    "hash": "8d36882730bbe907d4097443e83d0e7841bb87a1"
  },
  {
    "path": "assets/gestures/right/ok.webp",
    "hash": "4fc1322e400112847dc33310e9d15bff9b822acd"
  },
  {
    "path": "assets/gestures/right/palmar_four.webp",
    "hash": "b5a6e2b105b89d2ea476c4bce60e35beb9ff8f5c"
  },
  {
    "path": "assets/gestures/right/palmar_gun.webp",
    "hash": "3be4c950079a1cb4d93bfac2500dfcc6694b7400"
  },
  {
    "path": "assets/gestures/right/palmar_ok.webp",
    "hash": "8336c7a6eb69ab725a84dd8f181995715bdb6d3b"
  },
  {
    "path": "assets/gestures/right/palmar_paper.webp",
    "hash": "7fc03dd8c4c63b425a79c244ef762b04a4d1086f"
  },
  {
    "path": "assets/gestures/right/palmar_rock.webp",
    "hash": "6835300b89bebb90f670600e62cd1de117154502"
  },
  {
    "path": "assets/gestures/right/palmar_scissors.webp",
    "hash": "4be2d0220f0deae68ec9ead2a111a282aab43133"
  },
  {
    "path": "assets/gestures/right/paper.webp",
    "hash": "d7c5642b654f0e8d5b4590ee81f3d4149fc1ab0d"
  },
  {
    "path": "assets/gestures/right/rock.webp",
    "hash": "2147395f57e9feafb1e17f3673ace426df6716ed"
  },
  {
    "path": "assets/gestures/right/scissors.webp",
    "hash": "a3a3961b36b50c832ed15c7cd1e24164ebc29041"
  },
  {
    "path": "assets/gestures/right/thumbsdown.webp",
    "hash": "6bb6874e7af016613f2f83e5a3b37e13ebdede21"
  },
  {
    "path": "assets/gestures/right/thumbsup.webp",
    "hash": "590513b3cd4c7673cbba4bcd8d84532a5ec587be"
  },
  {
    "path": "assets/icons/back.png",
    "hash": "fa0524635c96dfd22d9d4229c365d88d5e6e2a8a"
  },
  {
    "path": "assets/icons/menu.png",
    "hash": "b8dbac1837b8c716d195b9046f54cbd2b28353b1"
  },
  {
    "path": "assets/loader-brain.png",
    "hash": "956b55a3631b58c150a91c4bf3452d4ac2282467"
  },
  {
    "path": "assets/loader-brain.webp",
    "hash": "9cd735063f5bb2916d1e36c88709b4280916b20b"
  },
  {
    "path": "icons/apple-touch-icon.png",
    "hash": "6779babaf514eed52ea6d5a8a7a10a93010d729e"
  },
  {
    "path": "icons/icon-1024.png",
    "hash": "917c980d67571dbb47c7a8f6c5dce42138d3420f"
  },
  {
    "path": "icons/icon-192.png",
    "hash": "d98cb09acf29576de776e91ba2035bb07b58318e"
  },
  {
    "path": "icons/icon-512.png",
    "hash": "a49c667e116c75a1dc624602790bea9fff6a87ed"
  },
  {
    "path": "icons/icon-maskable-1024.png",
    "hash": "0b54c99bf43f5accb749b439a99c770e2fab2fc8"
  },
  {
    "path": "icons/icon-maskable-512.png",
    "hash": "e24ebf1a689580ca1772ee1ec5429399389f2c0d"
  }
];

importScripts('js/worker-runtime.js');

createCognitiveWorker({
  self,
  appCacheName: APP_CACHE_NAME,
  mediaCacheName: MEDIA_CACHE_NAME,
  assetPaths: APP_ASSET_PATHS,
  mediaAssetPaths: MEDIA_ASSET_PATHS
});
